services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    command: [
      "-path", "/migrations",
      "-database", "mysql://root:root@tcp(db:3306)/orders_db",
      "up"
    ]
    volumes:
      - ./migrations:/migrations
    depends_on:
      db:
        condition: service_healthy

  app:
    build: .
    environment:
      DATABASE_URL: "root:root@tcp(db:3306)/orders_db"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "50051:50051"

volumes:
  db_data:
